comment:
  layout: "header, diff,tree,files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  branches: null
  flags: null
  paths: null

ignore:
  - "src/main/java/unq/eis/dao"
  - "src/main/java/unq/eis/service"
