language: java

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

sudo: false # faster builds

before_script:
  - mysql -e 'CREATE DATABASE unquiflix;'

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)